In [1]:
import pandas as pd
pd.read_parquet("../data/bronze/currencies")

,id,name,short_code,code,precision,subunit,symbol,symbol_first,decimal_mark,thousands_separator,_ingested_at,_source_file,_batch_id
0,1,UAE Dirham,AED,784,2,100,د.إ,True,.,",",2026-03-29 08:38:31.395841,https://api.currencybeacon.com/v1/currencies,20260329_083813
1,2,Afghani,AFN,971,2,100,؋,False,.,",",2026-03-29 08:38:31.395841,https://api.currencybeacon.com/v1/currencies,20260329_083813
2,3,Lek,ALL,8,2,100,L,False,.,",",2026-03-29 08:38:31.395841,https://api.currencybeacon.com/v1/currencies,20260329_083813
3,4,Armenian Dram,AMD,51,2,100,դր.,False,.,",",2026-03-29 08:38:31.395841,https://api.currencybeacon.com/v1/currencies,20260329_083813
4,5,Netherlands Antillean Guilder,ANG,532,2,100,ƒ,True,",",.,2026-03-29 08:38:31.395841,https://api.currencybeacon.com/v1/currencies,20260329_083813
...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,157,CFP Franc,XPF,953,0,1,Fr,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
479,158,Yemeni Rial,YER,886,2,100,﷼,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
480,159,Rand,ZAR,710,2,100,R,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
481,160,Zambian Kwacha,ZMW,967,2,100,ZK,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
482,161,Zimbabwe Dollar,ZWL,932,2,100,$,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632

In [2]:
import pandas as pd
pd.read_parquet("../data/bronze/rates")

,currency,rate,rate_date,_ingested_at,_source_file,_batch_id,curr_base
0,SOS,155.6070039800,2026-03-29 08:38:44,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,AED
1,BBD,0.5445881600,2026-03-29 08:38:44,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,AED
2,SDG,163.4289028300,2026-03-29 08:38:44,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,AED
3,AWG,0.4874064000,2026-03-29 08:38:44,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,AED
4,BIF,808.2374107100,2026-03-29 08:38:44,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,AED
...,...,...,...,...,...,...,...
76795,ERN,0.0002365600,2026-03-29 08:39:00,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,ZWL
76796,ALL,0.0013145000,2026-03-29 08:39:00,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,ZWL
76797,GNF,0.1384633200,2026-03-29 08:39:00,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,ZWL
76798,PGK,0.0000678600,2026-03-29 08:39:00,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,ZWL
76799,SLL,0.3608371700,2026-03-29 08:39:00,2026-03-29 08:39:08.612998,https://api.currencybeacon.com/v1/latest,20260329_083907,ZWL

In [3]:
import pandas as pd
pd.read_parquet("../data/silver/currencies")

,id,name,short_code,code,precision,subunit,symbol,symbol_first,decimal_mark,thousands_separator,_ingested_at,_source_file,_batch_id
0,1,UAE Dirham,AED,784,2,100,د.إ,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
1,2,Afghani,AFN,971,2,100,؋,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
2,3,Lek,ALL,008,2,100,L,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
3,4,Armenian Dram,AMD,051,2,100,դր.,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
4,5,Netherlands Antillean Guilder,ANG,532,2,100,ƒ,True,",",.,2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283,157,CFP Franc,XPF,953,0,1,Fr,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
1284,158,Yemeni Rial,YER,886,2,100,ریال,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
1285,159,Rand,ZAR,710,2,100,R,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
1286,160,Zambian Kwacha,ZMW,967,2,100,ZK,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
1287,161,Zimbabwe Dollar,ZWL,932,2,100,$,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632

In [4]:
import os
import pandas as pd

if os.path.exists('../data/silver/currencies_quarantine'):
    pd.read_parquet('../data/silver/currencies_quarantine')
else:
    print('No currency quarantine data')

No currency quarantine data

In [5]:
import pandas as pd
pd.read_parquet("../data/silver/rates")

,currency,rate,rate_date,_ingested_at,_source_file,_batch_id,curr_base
0,MWK,472.6034663400,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
1,GEL,0.7409335200,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
2,BWP,3.7102857200,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
3,JMD,42.7824352200,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
4,HUF,91.7679185200,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
...,...,...,...,...,...,...,...
230395,UGX,0.0588313500,2026-03-29 17:01:07,2026-03-29 17:01:20.764574,https://api.currencybeacon.com/v1/latest,20260329_170119,ZWL
230396,SYP,0.0017430800,2026-03-29 17:01:07,2026-03-29 17:01:20.764574,https://api.currencybeacon.com/v1/latest,20260329_170119,ZWL
230397,CAD,0.0000218500,2026-03-29 17:01:07,2026-03-29 17:01:20.764574,https://api.currencybeacon.com/v1/latest,20260329_170119,ZWL
230398,SGD,0.0000203200,2026-03-29 17:01:07,2026-03-29 17:01:20.764574,https://api.currencybeacon.com/v1/latest,20260329_170119,ZWL
230399,CLF,3.700E-7,2026-03-29 17:01:07,2026-03-29 17:01:20.764574,https://api.currencybeacon.com/v1/latest,20260329_170119,ZWL

In [6]:
import os
import pandas as pd

if os.path.exists('../data/silver/rates_quarantine'):
    pd.read_parquet('../data/silver/rates_quarantine')
else:
    print('No rates quarantine data')

No rates quarantine data