In [1]:
import pandas as pd
import psycopg
import os
from dotenv import load_dotenv

load_dotenv()

PG_HOST     = os.environ.get("DB_HOST")
PG_PORT     = os.environ.get("DB_PORT")
PG_DB       = os.environ.get("DB_DATABASE")
PG_USER     = os.environ.get("DB_USERNAME")
PG_PASSWORD = os.environ.get("DB_PASSWORD")

conn_string = f"host={PG_HOST} port={PG_PORT} dbname={PG_DB} user={PG_USER} password={PG_PASSWORD}"

conn = psycopg.connect(conn_string)
df = pd.read_sql('SELECT * FROM public_gold.fact_rates LIMIT 100', conn)
df.head()

C:\Users\Tanel\AppData\Local\Temp\ipykernel_14988\590923641.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql('SELECT * FROM public_gold.fact_rates LIMIT 100', conn)

         date_key curr_base currency       rate
0  20260319070316       TWD      DZD   4.150865
1  20260319070316       TWD      GIP   0.023367
2  20260319070316       TWD      MWK  54.490015
3  20260319070316       TWD      HNL   0.832620
4  20260319070316       TWD      MXN   0.556139

In [5]:
query = """
SELECT d.date, f.curr_base, f.currency, f.rate
FROM public_gold.fact_rates f
JOIN public_gold.dim_date d ON f.date_key = d.date_key
"""
df = pd.read_sql(query, conn)
print(len(df))
df.head(2000)

C:\Users\Tanel\AppData\Local\Temp\ipykernel_14988\185094746.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

51200

                    date curr_base currency       rate
0    2026-03-19 19:20:16       TWD      DZD   4.150865
1    2026-03-19 19:20:16       TWD      GIP   0.023367
2    2026-03-19 19:20:16       TWD      MWK  54.490015
3    2026-03-19 19:20:16       TWD      HNL   0.832620
4    2026-03-19 19:20:16       TWD      MXN   0.556139
...                  ...       ...      ...        ...
1995 2026-03-19 19:20:09       NIO      MZN   1.736552
1996 2026-03-19 19:20:09       NIO      FJD   0.060941
1997 2026-03-19 19:20:09       NIO      GTQ   0.208591
1998 2026-03-19 19:20:09       NIO      USD   0.027206
1999 2026-03-19 19:20:09       NIO      TTD   0.184513

[2000 rows x 4 columns]