In [6]:
import pandas as pd
import psycopg
import os
from dotenv import load_dotenv

load_dotenv()

PG_HOST     = os.environ.get("DB_HOST")
PG_PORT     = os.environ.get("DB_PORT")
PG_DB       = os.environ.get("DB_DATABASE")
PG_USER     = os.environ.get("DB_USERNAME")
PG_PASSWORD = os.environ.get("DB_PASSWORD")

conn_string = f"host={PG_HOST} port={PG_PORT} dbname={PG_DB} user={PG_USER} password={PG_PASSWORD}"

conn = psycopg.connect(conn_string)
df = pd.read_sql('SELECT * FROM public_gold.fact_rates LIMIT 100', conn)
df.head(500)

C:\Users\Tanel\AppData\Local\Temp\ipykernel_6248\1369390132.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql('SELECT * FROM public_gold.fact_rates LIMIT 100', conn)

          date_key curr_base currency       rate
0   20260518030527       TWD      AED   0.116262
1   20260518030527       TWD      AFN   1.992645
2   20260518030527       TWD      ALL   2.599849
3   20260518030527       TWD      AMD  11.651582
4   20260518030527       TWD      ANG   0.057027
..             ...       ...      ...        ...
95  20260518030527       TWD      MUR   1.496781
96  20260518030527       TWD      MVR   0.489082
97  20260518030527       TWD      MWK  54.877516
98  20260518030527       TWD      MXN   0.548132
99  20260518030527       TWD      MYR   0.125896

[100 rows x 4 columns]

In [5]:
query = """
SELECT d.date, f.curr_base, f.currency, f.rate
FROM public_gold.fact_rates f
JOIN public_gold.dim_date d ON f.date_key = d.date_key
"""
df = pd.read_sql(query, conn)
print(f'Total rates in gold: {len(df)}')
df.head(2000)

Total rates in gold: 25600

C:\Users\Tanel\AppData\Local\Temp\ipykernel_6248\2317374506.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

                    date curr_base currency       rate
0    2026-05-18 15:14:27       TWD      AED   0.116262
1    2026-05-18 15:14:27       TWD      AFN   1.992645
2    2026-05-18 15:14:27       TWD      ALL   2.599849
3    2026-05-18 15:14:27       TWD      AMD  11.651582
4    2026-05-18 15:14:27       TWD      ANG   0.057027
...                  ...       ...      ...        ...
1995 2026-05-18 15:14:34       MYR      BND   0.321693
1996 2026-05-18 15:14:34       MYR      BOB   1.742799
1997 2026-05-18 15:14:34       MYR      BOV        NaN
1998 2026-05-18 15:14:34       MYR      BRL   1.260613
1999 2026-05-18 15:14:34       MYR      BSD   0.251456

[2000 rows x 4 columns]